language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=~/builds/kishoreyekkanti/RapidFTR---Android/android-sdk_r20.0.3-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  10 = 2.2 or API level 8
  - android list sdk
  - android update sdk --filter 1,2,10 --no-ui --force

notifications:
  irc: "irc.freenode.org#rapidftr"